version: "3.4"
services:
  swoft:
    build: .
    # for local develop is open `command`
    # command: php -S 127.0.0.1:13300
    container_name: swoft-srv
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    depends_on:
      - mysql
      - redis
      - consul
    ports:
      - "18306:18306"
      - "18307:18307"
      - "18308:18308"
    volumes:
      - ./:/var/www/swoft
      - ./runtime/ng-conf:/etc/nginx
      - ./runtime/logs:/var/log

  mysql:
    image: mysql:8.0.19
    container_name: mysql-srv
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "13306:3306"
    volumes:
      - ./runtime/data/mysql:/var/lib/mysql

  redis:
    container_name: redis-srv
    image: redis:4-alpine
    ports:
      - "16379:6379"
    sysctls:
      net.core.somaxconn: 65535

  consul:
    image: consul:1.8.0
    container_name: consul-srv
    environment:
      - CONSUL_BIND_INTERFACE:eth0
    ports:
      - "18500:8500"

  go:
    image: golang:1.14.4-stretch
    container_name: golang-srv
    volumes:
      - ./go:/go/src
    tty: true
    stdin_open: true

  mq:
    image: rabbitmq:3.8.5
    container_name: rabbitmq-srv
    ports: 
      - "15672:5672"
    
  kong-database:
    image: postgres:9.6
    ports: 
      - "5432:5432"
    environment: 
      - "POSTGRES_USER=kong"
      - "POSTGRES_DB=kong"
      - "POSTGRES_PASSWORD=kong"

  kong:
    image: kong:2.0.5-alpine
    container_name: kong-srv
    depends_on: 
      - kong-database
    ports: 
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment: 
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=kong-database"
      - "KONG_PG_DATABASE=kong"
      - "KONG_PG_USER=kong"
      - "KONG_PG_PASSWORD=kong"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
    # command: "kong migrations bootstrap"
    