version: "3.4"
services:
  swoft:
    build: .
    # for local develop is open `command`
    command: php -S 127.0.0.1:13300
    container_name: swoft-srv
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    depends_on:
      - mysql
      - redis
      - consul
    ports:
      - "18306:18306"
      - "18307:18307"
      - "18308:18308"
    volumes:
      - ./:/var/www/swoft
      - ./runtime/ng-conf:/etc/nginx
      - ./runtime/logs:/var/log

  mysql:
    image: mysql:8.0.19
    container_name: mysql-srv
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "13306:3306"
    volumes:
      - ./runtime/data/mysql:/var/lib/mysql

  redis:
    container_name: redis-srv
    image: redis:4-alpine
    ports:
      - "16379:6379"
    sysctls:
      net.core.somaxconn: 65535
    
  consul:
    image: consul:1.8.0
    container_name: consul-srv
    environment: 
      - CONSUL_BIND_INTERFACE:eth0
    ports:
      - "18500:8500"